language: node_js
node_js:
- node
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --aot --prod --progress="false"
after_success:
- npm --prefix ./functions install ./functions
- firebase deploy --token $TOKEN
env:
  global:
    secure: iUQgjmgOFiKkwlTWSpVbslP6RxtLDjR+yQrD3tFDHkxsPSCxlDLPmseyKeIPX19qjZ/tCRRVaz+LWeDc0tr2eQPX1GIYd6FpmZs+KZ/cRjiw+mNeUUrpPBGbVhgb10x0xHPj4vD3f2Hk7OlzX/fn3OZE3uUzj4lagPQvb45cQ4m603itAMeZWGvBCRqSX/cQBs/9M4EzvVui4iwGYx+pSP2KBB65+hV6oq2VzuuKK10xRo/k9B3Mf5ldTjeCYKaKqGBSKiOcTZq7MpOUsErK4RK4xqRcsfXoTxceIoRNcYlLuejqsoePhP4wOj6nmIfYNRubLXJzLtqJNAI7ZHit4M2nGISDpSDrzcKTL/o03GZ/32GMe8Ps+YvU6s0yUAA928ie5VUHhWdkPzhIGG5+Hz6LmyjW6N6WhYczSKQ0zUr7U7ywwqGV/G8fumOPMNDeIPZHcZw2xQYUkk5md0hCMlVPTQiclKwcUevRnTZerwAE1wQ+lF9o/IyfzW3l3T4fppU1HOUQL6snGRizkAr4E7T85WQF6wy+NToMgsgQuSOFfqwW4f9jB1es8c+Z3ws2mtOmOB/WrnBYVZnVYhPP6xW4e3hbugWapz+mVayQg2C+X01rofShbEUmQ4e0B8XNCLg027I92VJaTCCcNwRuHHldeWxv6X4HYOAB7XOlQDs=
