language: node_js
node_js:
- node
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --aot --prod --progress="false"
after_success:
- firebase deploy --token $FIREBASE_TOKEN
deploy:
  provider: firebase
  token:
    secure: BhJwFBmH8gMbE04Am9pHYlo9ZXN1JSzlsSkfTpj772LSEgNVn6XSEY3fh2wrHIl1FwB9X4T6pMX1xTYcm8ibgmb4Y7LiXcVXNIHtK0vlFJQ8g29Ut1SJgVp1pmfAYS+lxlEx1RH8CD33U6VEOqtXU8ip4YCz2h/pHuiaOyAC7Y7ksmqKmOuLY/Ma3TQEnZscTaSJFsvszK7l28XPOtUk+clCFia4/qw6ZWuK+KeFQj6kOGWOAXs40pvOHjLdyEaxXaYlWF9qASYBauz+sdDdsKCfXfXaUxl4F6T5hNsjyV7mAsug45Bs87QdvI6vNMrtvo5rnU857fYyD0u4/kE7M45FPPEQcQpgwQ9xtp5uWWzivEr0KtoF8uHjQ2H6jxzHGtXW8w3NGOxlizhjrVjHuolfcHbgZBnUA8Fi6t/H+bJMjU5X6P2dZU24oE+VxJVOLosuV9u28K3w0gOM7jaE2p6EHsRYsr+B4qKn3u8ggx4zMIr9F5wT3qDPjRx3Qs565B/2yfN2i1vmwbpek7686sy3fuPHlujSBbnxj6HuGI9rDXVw/BuJSldJ+D1cbswnUxs8K95c8m7HqHobPNpRhWMZpnUCzmNTIPKkm6T+cDdVjoTlJFZU0dKBhKchutWwgIIIovjwnrs1esAyJG1kVR5BfytkcMGG/JUgez9MYEs=
  project: nashor-luc
