language: node_js
node_js:
- node
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --aot --prod --progress="false"
deploy:
  provider: firebase
  token:
    secure: TEDIYLUGTbpcW07+VOX3VgOiIdEDVYykW9W25c5ZT+DMVko/DhiTIXaN5Oa7+WEuGrmH/01gmAlZknGIl6B6HxYaU8AzAd7MFm+vIZJNhEcRmFg5pD60ZlHjVg3jWvsoOZxMA+ONnFwB8vbyOkc1BOsYGYSF54K27QGKQ9RmBxpgN3tNONJnbqETmA1BzU5JyDEsD/85J+KgOe5U1ZSVW8meNA7wt73hEb7rdloNAIvCmj6wh3ZTU/B6x7lbS1lDrypYBOBcrpzq3Vl7CN4HLZS6iCBTfF3S3qzxkBxD2QSq8z+mIWmeGdMSiOsMiT1oOzh8afnjVeAoyHEwQ/0zt+e53CWPTMP2RqlWI4GvuSPkUf1X1s60terNZFCuWY0GHLKpyWL8z09R39zK+JbZvx34BkTw0uWmw9Xe4GTDO8ycRu9tP/gOZDfoPeE0d+6iSlSY4zPTwu/naMoUP4GktpBp8pTgmEP1/X39gUygT9faNaT+VziGt6dVpEpeDNI9YATaIh+yNaXeQspefLTlTdcSRQDQfrXRjs7SKyodkbjp6kFYe27j4cEOHqrFnmIzHDG7ROqZiXmXG49hzydKa94WkSFra6z1W6WQLFunA+ZqTnl1vV2LhhWLJg4bwESsfSj6LV4qgWvrLPRRyv2PPdd9kKGybxtLGneAu+brVgE=
  project: nashor-luc
