language: node_js

node_js:
- node

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli
  - openssl aes-256-cbc -K $encrypted_44f31267353f_key -iv $encrypted_44f31267353f_iv
  -in deploy_key.enc -out deploy_key -d

script: bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: 44f31267353f
  - COMMIT_AUTHOR_EMAIL: florian.richter@sap.com
