language: node_js

node_js:
- node

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script: bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: 44f31267353f
  - COMMIT_AUTHOR_EMAIL: florian.richter@sap.com
