language: node_js
node_js:
- node
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- ng build --aot --prod --progress="false"
deploy:
  provider: firebase
  token:
    secure: FB_TOKEN
  project: nashor-luc
env:
  global:
    secure: OnO3ohgGlsrxUIYAydeMlkrsToxioC3JVfWMgpFGwWOHfQQd/mgvx4td86+E3re6IKboL+yFgmbtCGlrZPNgoX5jjQp+NjzzrWyu/SUdBEve9lbE620lVY1Rx4ubOkznqJyR4Y2LNvkqXvElC0UABZ4Udle92KFyJS0JUjBPto4kH9nIdj4rkIwvuqRDUASGvXIDlK98KmQ7jQuSdIOmO33PXRLX4rMydzceHTL624B1gDCcInw8WKMpSifPwhFV9+3wn/zbXtaHYYvOd2Ypju8icui0ycZ4DAti8NfOcWHjGltIh0UkrlS/BJxu4n6Z1aUW8qKSJcT8BB/XhGlXIkyg+Sv2+c5/5MH2cvlcMI2WWQioOcgi3hpJE0seEGYSSEGqOopa1OJm0Jcj8xnbb/Uhj3TN346PcTGV0ZtM3bdWphNYxBNcqpjA5hL3R6xfnHhyNgxUP0ZHTG/LLLYPVCKaRwNrotrX7gyk3+Lbt0E5kElQ025Ha7necQB/S6df7LBCmf/9wjciMcOdi9uYEr1MggZvtRTyqvLPOyXW7EuVTn+pbx64MiLVmYY760bc0LmmSj9wt+bdssWb3Ixmgx2wfRM6CyXJQDvpPbXqrk/zs/71b/XvIy82vQDs3Ovl7kTS8Ql9BMSWcUdbpbnhqwS8D/swo0VTSjmjvQ2j1p8=
